title          : "Dr. Semmelweis and the discovery of handwashing"
description    : >
  Reanalyse the data behind one of the most important discoveries of modern medicine: Handwashing.
long_description: |
  In 1847 the Hungarian physician Ignaz Semmelweis makes a breakthough discovery: He discovers handwashing. Contaminated hands was a major cause of childbed fever and by enforcing handwashing at his hospital he saved hundreds of lives. 

  In this python project we will reanalyze the medical data Semmelweis collected. This project assumes you are familiar with pandas DataFrames and bootstrap analysis. You can learn the required skills in these courses:

  - <a href="https://www.datacamp.com/courses/intermediate-python-for-data-science" target="_blank">Intermediate Python for Data Science</a>
  - <a href="https://www.datacamp.com/courses/pandas-foundations" target="_blank">pandas Foundations</a>
language       : python
from           : 'python-notebooks-prod:109'
runtime_config : default
state          : live
technology: 2
instructors:
  - rasmus@datacamp.com
collaborators: []
prerequisites:
  - 799
  - 1639
difficulty_level: 2
topics:
  - 3
  - 4
  - 12
time_needed: "60 minutes"
illustration: "https://s3.amazonaws.com/assets.datacamp.com/production/project_20/datasets/project_image.png"
